### ISSUE TITLE
HTML frame for annotation view [3]

### ISSUE THREAD

**Issue by JoROSU** [svrhovac/videoAnnotations#15]

**Comment by JoROSU** [comment]
First version done.
Some small changes in design are needed.

**Comment by svrhovac** [comment]
Are these changes in design agreed? Is this task completed?

**Comment by Milica-44** [comment]
This task is in progress.
Milica and I are working on final design. It will be two versions, so you can decide which will be implemented. 
Budo, Natasa and Slobo are working on HTML and CSS code.
