### ISSUE TITLE
Zahtjev za listu od 1.000.000 objekata [1]

### ISSUE THREAD

**Issue by svrhovac** [svrhovac/videoAnnotations#4]
Nekoliko pitanja za razmišljanje:
1. Da li ste predvidjeli šta ako u bazi imate veliki broj videa, da li će servis da vrati sve lideo u jednoj listi?
2. Da li kad klijent traži koliko da preskoči i koliko da vrati, da li uzimate ovaj broj bez ikakvih kriterijuma?

**Comment by levonkeleman** [comment]
1. Razmotrili smo taj problem u fazi razrade projekta, osmislili rjesenje (od servera se zatrazi fiksan broj videa, prikaze se u listi na kraju koje ima dugme da se zatrazi novi batch), medjutim nismo uspjeli da implementiramo zbog nedostatka vremena.

**Comment by kormang** [comment]
na serveru postoji ogranicenje da skip i limit ne mogu biti manji od 0. Potrebno je prepraviti da limit bude minimalno 1, jer 0 znaci neograniceno, a maksimalno i podrazumjevano npr: 50.

**Comment by svrhovac** [comment]
Ispravno je odrediti maksimalnu granicu koliko se objekata može zatražiti, ali ostaviti da klijent u tim granicama može da određuje koliko objekata da mu se vrati.

**Comment by kormang** [comment]
pa da, to sam i mislio
